### ISSUE TITLE
Limiting pages to a set amount of entries

### ISSUE THREAD

**Issue by Alcrafter-YT** [blitzdose/MinecraftServerRemote#13]
**Is your feature request related to a problem? Please describe.**
At some point, if the plugin/webinterface runs for an extended amount of time on a medium to large server, some pages run into issues. The log page for example just gets a little full and takes ages to load, I've had this problem several times now and my solution always was to clear the logs manually. Also, if there are many players on at the same time(10-20+) the home page gets extended further and further down, which doesn't really help performance or the overall look of the page.

**Describe the solution you'd like**
Limit the amount of log entries/players displaying on these pages. A good number of players for the home page, at least from my testing, is 8 because this still lets you see a good amount of players and doesn't extend too far down. Also, if you really want to see all players and take specific actions, then you can always go to the players tab and do it there. For the log it's the same solution, just display a few, maybe 50-60 which would still give you enough info and loads pretty fast.

**Describe alternatives you've considered**
Another solution for the log is to implement a system to remove all log entries older than x days, or remove all log entries every x days. You could also consider a paging system where you can like change from page one to two and so on, but I don't know how hard that would be to implement. If you're considering the system with pages, you could also do that with the players tab to make it easier to use when there are only 20-30 players on each page, but that's just a side note.

**Comment by blitzdose** [comment]
The displayed players on the home page is already limited to 8
