### ISSUE TITLE
Edited files are not saved on Apple devices

### ISSUE THREAD

**Issue by Alcrafter-YT** [blitzdose/MinecraftServerRemote#16]
**Describe the bug**
Now that scrolling works on Apple devices, saving edits in files seems to be broken.

**Edit**
This is __not only Apple devices__ but also Windows and Android, just tested with my computer/phone and got the same results.

**To Reproduce**
1. Go to FTP with an Apple device
2. Click on a file and edit it
3. Scroll down and save the edit
4. See that the edits aren‘t saved

**Expected behavior**
I would expect the edits I do in a file to be saved and not reset to what it was previously.

**Minecraft-Server (please complete the following information):**
 - OS: Ubuntu
 - Plugin-Version: 3.3

**Device (please complete the following information):**
 - Device: Apple IPad 8
 - OS: IPadOS 15.2.1
 - Plugin-Version: 3.3

**Comment by blitzdose** [comment]
### Documentation
Does affect other devices too

**Comment by blitzdose** [comment]
Fixed with Version 3.3.1
