### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by blitzdose** [blitzdose/MinecraftServerRemote#17]
It looks like the Plugin is using a lot of CPU Power.
Find what is causing that and fix it.

**Comment by Zzeyy** [comment]
![image](https://user-images.githubusercontent.com/97387354/151057098-a3eb863c-cad9-4bdd-81db-e610ff9b3623.png)
![image](https://user-images.githubusercontent.com/97387354/151057108-a38419a3-4585-44cd-bbc1-fea4806120d2.png)

From Aikar's Timings

**Comment by blitzdose** [comment]
Fixed in the next release
