### ISSUE TITLE
Temporary download files aren't removed

### ISSUE THREAD

**Issue by Alcrafter-YT** [blitzdose/MinecraftServerRemote#24]
**Describe the bug**
The files in ./plugins/MinecraftServerRemote/html/tmp aren't removed, this leads to them slowly stacking up over time when you don't clear them. I myself just noticed it because my server was over 20GB bigger than it should be.

**To Reproduce**
1. Go to 'FTP'
2. Download serveral files at once so it creates a zip archive
3. Check the above folder and see that the zip is still stored there despite the download being finished

**Expected behavior**
Temporary files should be removed when the download is finished or when the server restarts so they don't junk your server full with unneeded stuff.

**Minecraft-Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - Plugin-Version: latest

**Comment by blitzdose** [comment]
What kind of Files are there? These should get cleared.

**Comment by Alcrafter-YT** [comment]
> What kind of Files are there? These should get cleared.

They are .zip files, the ones that you get when downloading more than one file at once.

**Comment by blitzdose** [comment]
These _should_ get cleared once the file is actually downloaded. Did you changed some permissions of the files or folders?

**Comment by Alcrafter-YT** [comment]
> These _should_ get cleared once the file is actually downloaded. Did you changed some permissions of the files or folders?

No, it shouldn't be a file permission issue. It could be that the files weren't downloaded correctly or fully cause some of my staff may have canceled their download. Easy fix for that would be to just delete all the temporary files when the plugin enables, just to prevent them stacking up like this because canceling a download just happens sometime.
