### ISSUE TITLE
update to 1.18

### ISSUE THREAD

**Issue by Enderkries2011** [blitzdose/MinecraftServerRemote#25]
I want the plugin to be updated I have a server on 1.18.2 and I wish that it would happen 

I want the plugin to be updated to 1.18 and 1.18.2

Making it work on 1.18

I also may like a debug screen with ftp or some

**Comment by blitzdose** [comment]
I will update everything to the newest version but it will take some time. At the moment I don't have any time for these projects. You can join the Discord to stay up to date if I start working on it again: https://discord.gg/SewjCwVpaa
